export const products = [
  {
    id: 1,
    title: "Product 1",
    price: 100,
    description: "Description 1",
  },
  {
    id: 2,
    title: "Product 2",
    price: 150,
    description: "Description 2",
  },
  {
    id: 3,
    title: "Product 3",
    price: 200,
    description: "Description 3",
  },
  {
    id: 4,
    title: "Product 4",
    price: 250,
    description: "Description 4",
  },
  {
    id: 5,
    title: "Product 5",
    price: 300,
    description: "Description 5",
  },
  {
    id: 6,
    title: "Product 6",
    price: 350,
    description: "Description 6",
  },
  {
    id: 7,
    title: "Product 7",
    price: 400,
    description: "Description 7",
  },
  {
    id: 8,
    title: "Product 8",
    price: 450,
    description: "Description 8",
  },
  {
    id: 9,
    title: "Product 9",
    price: 500,
    description: "Description 9",
  },
  {
    id: 10,
    title: "Product 10",
    price: 550,
    description: "Description 10",
  },
  {
    id: 11,
    title: "Product 11",
    price: 600,
    description: "Description 11",
  },
  {
    id: 12,
    title: "Product 12",
    price: 650,
    description: "Description 12",
  },
  {
    id: 13,
    title: "Product 13",
    price: 700,
    description: "Description 13",
  },
  {
    id: 14,
    title: "Product 14",
    price: 750,
    description: "Description 14",
  },
  {
    id: 15,
    title: "Product 15",
    price: 800,
    description: "Description 15",
  },
  {
    id: 16,
    title: "Product 16",
    price: 850,
    description: "Description 16",
  },
  {
    id: 17,
    title: "Product 17",
    price: 900,
    description: "Description 17",
  },
  {
    id: 18,
    title: "Product 18",
    price: 950,
    description: "Description 18",
  },
  {
    id: 19,
    title: "Product 19",
    price: 1000,
    description: "Description 19",
  },
  {
    id: 20,
    title: "Product 20",
    price: 1050,
    description: "Description 20",
  },
  {
    id: 21,
    title: "Product 21",
    price: 1100,
    description: "Description 21",
  },
];
